[profile.default]
src = "src"
out = "out"
solc = "0.8.25"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer-runs = 200

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
tes = "${TESCHAIN_RPC_URL}"
kite_testnet = "${KITE_AI_TESTNET_RPC_URL}" # Chain ID: 2368

[fmt]
int_types = "long"
line_length = 120

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
